# appveyor.yml
image: Ubuntu

clone_folder: /usr/go/src/github.com/shawn1m/overture

branches:
  only:
    - master

skip_tags: true

skip_branch_with_pr: true

environment:
  GOPATH: /usr/go/

stack: go 1.13

before_build:
  - "python3 ./build.py -create-sample"
  - "python3 ./build.py -build"

before_test:
  - go vet ./...

test_script:
  - go test ./...

artifacts:
  - path: 'overture-*.zip'